import sharp from 'sharp';
import fs from 'fs-extra';
import path from 'path';
import { ORIGINAL_DIR, SMALL_DIR } from './config';

export interface ProcessedImage {
    fileNameOriginal: string;
    fileNameSmall: string;
}

export const processImage = async (file: Express.Multer.File): Promise<ProcessedImage> => {
    await fs.ensureDir(ORIGINAL_DIR);
    await fs.ensureDir(SMALL_DIR);

    // file.filename was generated by multer's storage config (upload.ts) as a
    // random uuid + validated extension
    const timestamp = Date.now();
    const originalName = `${timestamp}-${file.filename}`;
    // La vignette est encodée en WebP plutôt qu'en JPEG
    const smallName = `${timestamp}-small-${path.parse(file.filename).name}.webp`;

    const originalPath = path.join(ORIGINAL_DIR, originalName);
    const smallPath = path.join(SMALL_DIR, smallName);

    try {
        // Save original.
        await fs.move(file.path, originalPath);

        // Generate and save small version.
        await sharp(originalPath)
            .rotate()
            .resize(400, 400, { fit: 'outside' })
            .webp({ quality: 80 })
            .toFile(smallPath);
    } catch (err) {
        await restoreFailedImage(file, originalName, smallName);
        throw err;
    }

    return {
        fileNameOriginal: originalName,
        fileNameSmall: smallName
    };
};

// En cas d'échec, le fichier reste disponible dans temp pour inspection,
// mais aucun fichier traité ne reste dans original ou small.
export async function restoreFailedImage(
    file: Express.Multer.File,
    fileNameOriginal: string,
    fileNameSmall: string
): Promise<void> {
    const originalPath = path.join(ORIGINAL_DIR, fileNameOriginal);
    const smallPath = path.join(SMALL_DIR, fileNameSmall);

    if (await fs.pathExists(originalPath) && !(await fs.pathExists(file.path))) {
        await fs.move(originalPath, file.path);
    }
    await fs.remove(originalPath);
    await fs.remove(smallPath);
}

