import sharp from 'sharp';
import fs from 'fs-extra';
import path from 'path';
import { ORIGINAL_DIR, SMALL_DIR } from './config';

export interface ProcessedImage {
    fileNameOriginal: string;
    fileNameSmall: string;
}

export const processImage = async (file: Express.Multer.File): Promise<ProcessedImage> => {
    // Ensure directories exist
    await fs.ensureDir(ORIGINAL_DIR);
    await fs.ensureDir(SMALL_DIR);

    // file.filename was generated by multer's storage config (upload.ts) as a
    // random uuid + validated extension
    const timestamp = Date.now();
    const originalName = `${timestamp}-${file.filename}`;
    // For small version, we force jpg extension since we convert to jpeg
    const smallName = `${timestamp}-small-${path.parse(file.filename).name}.jpg`;

    const originalPath = path.join(ORIGINAL_DIR, originalName);
    const smallPath = path.join(SMALL_DIR, smallName);

    try {
        // Save original
        await fs.move(file.path, originalPath);

        // Generate and save small version
        await sharp(originalPath)
            .rotate()
            .resize(400, 400, { fit: 'outside' })
            .jpeg({ quality: 80 })
            .toFile(smallPath);
    } catch (err) {
        // Ne laisse rien d'orpheline sur le disque si une des étapes échoue
        // (ex: image corrompue que sharp n'arrive pas à décoder).
        await Promise.all([
            fs.remove(originalPath).catch(() => {}),
            fs.remove(smallPath).catch(() => {}),
            fs.remove(file.path).catch(() => {}),
        ]);
        throw err;
    }

    return {
        fileNameOriginal: originalName,
        fileNameSmall: smallName
    };
};

// À appeler si l'image a bien été traitée (processImage a réussi) mais qu'une
// étape suivante échoue (ex: la transaction DB) — évite de laisser les
// fichiers déjà écrits sur disque sans ligne en base pour les référencer.
export const deleteProcessedImage = async (fileNameOriginal: string, fileNameSmall: string): Promise<void> => {
    await Promise.all([
        fs.remove(path.join(ORIGINAL_DIR, fileNameOriginal)).catch(() => {}),
        fs.remove(path.join(SMALL_DIR, fileNameSmall)).catch(() => {}),
    ]);
};
